### ISSUE TITLE
Module not found: Can't resolve '@noir-lang/barretenberg'

### ISSUE THREAD

**Issue by akornato** [noir-lang/noir-web-starter-next#1]
Running `npm i && npm run dev` and trying to open the page at http://localhost:3000/ throws. `Module not found: Can't resolve '@noir-lang/barretenberg'`. Same with `yarn && yarn dev`. BTW both `package-lock.json` and `yarn.lock` present.

**Comment by kobyhallx** [comment]
Thanks for the report @akornato
